# This is a config for E2B sandbox template.
# You can use template ID (4eymj86ej6o84gzy4xv5) or template name (codexa-nextjs-test-22) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("codexa-nextjs-test-22") # Sync sandbox
# sandbox = await AsyncSandbox.create("codexa-nextjs-test-22") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('codexa-nextjs-test-22')

team_id = "0d4856fe-97bb-41bd-8481-6de3244d9b10"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "codexa-nextjs-test-22"
template_id = "4eymj86ej6o84gzy4xv5"
